runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style

- url: /javascript
  static_dir: javascript

- url: .*
  script: main.app
  # login: default

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
